name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонировать репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установить зависимости
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Шаг 3: Запустить тесты
      - name: Run tests
        run: |
          pytest

      # Шаг 4: Проверка безопасности (Bandit)
      - name: Security check
        run: |
          pip install bandit
          bandit -r .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонировать репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Деплой (например, Heroku или сервер)
      - name: Deploy application
        run: |
          echo "Здесь напишите скрипт для деплоя"
